// Generated by https://transform.tools/json-to-typescript

export interface Tabs {
  id: number
  song_id: number
  song_name: string
  artist_id: number
  artist_name: string
  type: string
  part: string
  version: number
  votes: number
  difficulty: string
  rating: number
  date: string
  status: string
  preset_id: number
  tab_access_type: string
  tp_version: number
  tonality_name: string
  version_description: any
  verified: number
  recording: Recording
  album_cover: AlbumCover
  artist_cover: ArtistCover
  unique_chords: string
  ug_difficulty: string
  versions: Version[]
  userRating: number
  tuning: string
  capo: number
  urlWeb: string
  strumming: any[]
  videosCount: number
  comments_count: number
  contributor: Contributor
  advertising: Advertising
  versions_count: number
  pro_brother: ProBrother
  recommended: Recommended[]
  applicature: Applicature[]
  content: string
  official_tab_want: OfficialTabWant
  is_backing_track_under_review: boolean
}

export interface Recording {
  is_acoustic: number
  tonality_name: string
  performance: any
  recording_artists: any[]
  video_urls: any
  album_id: number
}

export interface AlbumCover {
  has_album_cover: boolean
  app_album_cover: AppAlbumCover
}

export interface AppAlbumCover {
  small: string
}

export interface ArtistCover {
  has_artist_cover: boolean
  app_artist_cover: AppArtistCover
}

export interface AppArtistCover {
  small: string
}

export interface Version {
  id: number
  song_id: number
  song_name: string
  artist_id: number
  artist_name: string
  type: string
  part: string
  version: number
  votes: number
  difficulty: string
  rating: number
  date: string
  status: string
  preset_id: number
  tab_access_type: string
  tp_version: number
  tonality_name: string
  version_description?: string
  verified: number
  recording: Recording2
  album_cover: AlbumCover2
  artist_cover: ArtistCover2
  unique_chords: string
  ug_difficulty: string
}

export interface Recording2 {
  is_acoustic: number
  tonality_name: string
  performance: any
  recording_artists: any[]
  video_urls: any
  album_id: number
}

export interface AlbumCover2 {
  has_album_cover: boolean
  app_album_cover: AppAlbumCover2
}

export interface AppAlbumCover2 {
  small: string
}

export interface ArtistCover2 {
  has_artist_cover: boolean
  app_artist_cover: AppArtistCover2
}

export interface AppArtistCover2 {
  small: string
}

export interface Contributor {
  user_id: number
  username: string
}

export interface Advertising {
  targeting_song_genre: string
}

export interface ProBrother {
  id: number
  song_id: number
  song_name: string
  artist_id: number
  artist_name: string
  type: string
  part: string
  version: number
  votes: number
  difficulty: string
  rating: number
  date: string
  status: string
  preset_id: number
  tab_access_type: string
  tp_version: number
  tonality_name: string
  version_description: any
  verified: number
  recording: Recording3
  album_cover: AlbumCover3
  artist_cover: ArtistCover3
  unique_chords: string
  ug_difficulty: string
}

export interface Recording3 {
  is_acoustic: number
  tonality_name: string
  performance: any
  recording_artists: any[]
  video_urls: any
  album_id: number
}

export interface AlbumCover3 {
  has_album_cover: boolean
  app_album_cover: AppAlbumCover3
}

export interface AppAlbumCover3 {
  small: string
}

export interface ArtistCover3 {
  has_artist_cover: boolean
  app_artist_cover: AppArtistCover3
}

export interface AppArtistCover3 {
  small: string
}

export interface Recommended {
  id: number
  song_id: number
  song_name: string
  artist_id: number
  artist_name: string
  type: string
  part: string
  version: number
  votes: number
  difficulty: string
  rating: number
  date: string
  status: string
  preset_id: number
  tab_access_type: string
  tp_version: number
  tonality_name: string
  version_description?: string
  verified: number
  recording: Recording4
  album_cover: AlbumCover4
  artist_cover: ArtistCover4
  unique_chords: string
  ug_difficulty: string
}

export interface Recording4 {
  is_acoustic: number
  tonality_name: string
  performance: any
  recording_artists: any[]
  video_urls: any
  album_id?: number
}

export interface AlbumCover4 {
  has_album_cover: boolean
  app_album_cover?: AppAlbumCover4
}

export interface AppAlbumCover4 {
  small: string
}

export interface ArtistCover4 {
  has_artist_cover: boolean
  app_artist_cover: AppArtistCover4
}

export interface AppArtistCover4 {
  small: string
}

export interface Applicature {
  chord: string
  variations: Variation[]
}

export interface Variation {
  id: string
  listCapos: ListCapo[]
  noteIndex: number
  notes: number[]
  frets: number[]
  fingers: number[]
  fret: number
  type: string
  baseDisplayNote: string
}

export interface ListCapo {
  fret: number
  startString: number
  lastString: number
  finger: number
}

export interface OfficialTabWant {
  artist_id: number
  song_id: number
  vote_count: number
}
